[package]
name = "oxisat-fuzz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oxisat = { path = "../oxisat" }
clap = { version = "3.2.21", features = ["derive"] }
rand = "0.8.5"
rand_pcg = "0.3.1"
